name: grader_followup
channels:
  - conda-forge
  - defaults
dependencies:
  - nodejs
  - ipython=8.2.0
  - notebook=6.2.0
  - jupyterlab=3.0.9
  - ipywidgets
  - widgetsnbextension
  - jupyterlab_widgets
  - nibabel=3.2.1
  - matplotlib=3.3.3
  - pandas=1.1.4
  - Pillow=9.1.0
  - scikit-image=0.17.2
  - scikit-learn
  - git=2.30.2
