name: grader_followup
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython=8.2.0
  - notebook=6.2.0
  - jupyterlab=3.0.9
  - ipywidgets=7.6.3
  - nibabel=3.2.1
  - matplotlib=3.3.3
  - pandas=1.1.4
  - Pillow=9.1.0
  - scikit_image=0.17.2
  - scipy=1.5.4
  - skimage
  - git=2.30.2
